### ISSUE TITLE
Remove my name as author

### ISSUE THREAD

**Issue by mikeshardmind** [unseenmagik/MagikCogsv3#1]
The modifications you have made at this point per the [license my code is distributed under](https://github.com/mikeshardmind/SinbadCogs/blob/master/License.md) require the removal of authorship while retaining attribution

https://github.com/unseenmagik/MagikCogsv3/blob/1443e2f8b13c16e36db4e13cfce09931782e7f85/embedmaker/embedmaker.py#L17

**Comment by unseenmagik** [comment]
Thanks Mike. Removed your name as Author.
