### ISSUE TITLE
Battleship Cog

### ISSUE THREAD

**Issue by Sashasonic** [unseenmagik/MagikCogsv3#6]
Hi there.. just installed your cog, as had missed the v2 game of this.. however, 2 things 1: I don't see a 'help' menu such as on your page here (like the 2 x embed as the v2 had it).

I had tried to play a game with the AI command, it sent the embed pic in the current channel, though also sent the game via pm.. not sure, so continued the 'game' in pm.. it just randomly stopped, with no prompt after about the 5th ship placed.. Then I also noticed that the channel also had posted the 'start' of a game.. where it also posted, "...You took too long, shutting down." (even though had also run a ship 'position' in the channel to be sure?

_When trying to add the cog to another of my redbots, I got this: The Battleship cog in the battleship.battleship package does not inherit from the commands.Cog base class. The cog author must update the cog to adhere to this requirement._

TIA.
nb: looks good btw

**Comment by unseenmagik** [comment]
this cog is no longer maintained
