### ISSUE TITLE
Read below

### ISSUE THREAD

**Issue by xDp64xG** [unseenmagik/MagikCogsv3#7]
Hey Magik, I've been trying to get ahold of you ever since my discord got hacked and deleted, so I lost ALL my contacts sadly, and been trying to find them again through various ways, lol. I don't know if you're on github anymore, but it was my last thing I can remember to try and contact you, Thx Magik:
xDp64xv2.0#6495

**Comment by unseenmagik** [comment]
> Hey Magik, I've been trying to get ahold of you ever since my discord got hacked and deleted, so I lost ALL my contacts sadly, and been trying to find them again through various ways, lol. I don't know if you're on github anymore, but it was my last thing I can remember to try and contact you, Thx Magik:
> xDp64xv2.0#6495

Hi @xDp64xG Just seen this message. Im not as active as I once was on Discord or Git but I am still around. 
I will drop you a DM.
